Repository OSGeo/grass-addons, pull requests merged in 2020-12, with the labels that each got.

#360 i.sentinel.coverage: fix potentially wrong output scene list
  grass7/imagery/i.sentinel/i.sentinel.coverage/i.sentinel.coverage.py
Labels: bug

#363 r.subdayprecip.design: no need to call v.db.addcolumn before v.to.db
  grass7/raster/r.subdayprecip.design/r.subdayprecip.design.py
Labels: bug

#370 v.in.redlist: lazy import of 'osgeo' module
  grass7/vector/v.in.redlist/v.in.redlist.py
Labels: Windows, bug

#369 v.in.pygbif: lazy import of 'osgeo' module
  grass7/vector/v.in.pygbif/v.in.pygbif.py
Labels: Windows, bug

#374 i.ann.maskrcnn: update installation command in docs
  grass7/imagery/i.ann.maskrcnn/i.ann.maskrcnn.html
Labels: bug, manual

#372 New addon: i.landsat toolset
  grass7/imagery/i.landsat/Makefile
  grass7/imagery/i.landsat/i.landsat.download/Makefile
  grass7/imagery/i.landsat/i.landsat.download/i.landsat.download.html
  grass7/imagery/i.landsat/i.landsat.download/i.landsat.download.py
  grass7/imagery/i.landsat/i.landsat.html
  grass7/imagery/i.landsat/i.landsat.import/Makefile
  grass7/imagery/i.landsat/i.landsat.import/i.landsat.import.html
  grass7/imagery/i.landsat/i.landsat.import/i.landsat.import.py
Labels: new addon
