Repository OSGeo/grass-addons, pull requests merged in 2020-11, with the labels that each got.

#331 v.what.strds.timestamp: add example
  grass7/vector/v.what.strds.timestamp/v.what.strds.timestamp.html
Labels: manual

#330 i.ann.maskrcnn.detect: lazy import skimade and PIL
  grass7/imagery/i.ann.maskrcnn/i.ann.maskrcnn.detect/i.ann.maskrcnn.detect.py
Labels: bug

#348 cronjob: generate manual sitemaps
  tools/cronjobs_osgeo_lxd/cron_grass78_releasebranch_78_build_bins.sh
Labels: manual

#352 i.sentinel.coverage + i.sentinel.parallel.download: new addons
  grass7/imagery/i.sentinel/i.sentinel.coverage/Makefile
  grass7/imagery/i.sentinel/i.sentinel.coverage/i.sentinel.coverage.html
  grass7/imagery/i.sentinel/i.sentinel.coverage/i.sentinel.coverage.py
  grass7/imagery/i.sentinel/i.sentinel.html
  grass7/imagery/i.sentinel/i.sentinel.parallel.download/Makefile
  grass7/imagery/i.sentinel/i.sentinel.parallel.download/i.sentinel.parallel.download.html
  grass7/imagery/i.sentinel/i.sentinel.parallel.download/i.sentinel.parallel.download.py
Labels: enhancement
