Repository OSGeo/grass-addons, pull requests merged in 2020-06, with the labels that each got.

#144 Fix v.delaunay3d compilation on FreeBSD
  grass7/vector/v.delaunay3d/Makefile
Labels: BSD

#200 i.modis.import: improve error handling input/files
  grass7/imagery/i.modis/i.modis.import/i.modis.import.py
Labels: enhancement

#199 i.modis.import: change cwd to input data dir
  grass7/imagery/i.modis/i.modis.import/i.modis.import.py
Labels: bug

#207 incomplete except/try for sentinelsat library presence
  grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py
Labels: bug

#208 i.zero2null manual: example added
  grass7/imagery/i.zero2null/i.zero2null.html
Labels: manual

#205 Add CI with build and test
  .github/workflows/apt.txt
  .github/workflows/build_grass.sh
  .github/workflows/ci.yml
  .github/workflows/requirements.txt
  .github/workflows/test.sh
Labels: Linux

#211 i.sentinel.mask manual: new example added with json support
  grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.html
  grass7/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.html
  grass7/imagery/i.sentinel/i.sentinel.mask/i.sentinel.mask.html
  grass7/imagery/i.sentinel/i.sentinel.mask/i_sentinel_mask_indonesia_esa_sen2cor.png
  grass7/imagery/i.sentinel/i.sentinel.mask/i_sentinel_mask_indonesia_grass_gis.png
Labels: manual

#214 i.sentinel.mask: predefine path to S2 band json file
  grass7/imagery/i.sentinel/i.sentinel.mask/i.sentinel.mask.html
  grass7/imagery/i.sentinel/i.sentinel.mask/i.sentinel.mask.py
Labels: enhancement

#216 grasslxd server: cronjobs hugo, snapshots, progman, addon manuals
  tools/cronjobs_osgeo_lxd/compile_addons_git.sh
  tools/cronjobs_osgeo_lxd/cron_grass78_releasebranch_78_build_bins.sh
  tools/cronjobs_osgeo_lxd/cron_grass78_src_relbr78_snapshot.sh
  tools/cronjobs_osgeo_lxd/cron_grass7_HEAD_build_bins.sh
  tools/cronjobs_osgeo_lxd/cron_grass7_HEAD_src_snapshot.sh
  tools/cronjobs_osgeo_lxd/cron_job_list_grass
  tools/cronjobs_osgeo_lxd/get_page_description.py
  tools/cronjobs_osgeo_lxd/googleebda3c3d501e9945.html
  tools/cronjobs_osgeo_lxd/grass-addons-index.sh
  tools/cronjobs_osgeo_lxd/hugo_clean_and_update_job.sh
  tools/cronjobs_osgeo_lxd/rsyncd.conf
  tools/cronjobs_osgeo_lxd/rsyncd.motd
Labels: addons, manual

#218 force lazy import where possible
  grass7/display/d.vect.colbp/d.vect.colbp.py
  grass7/display/d.vect.colhist/d.vect.colhist.py
  grass7/imagery/i.variance/i.variance.py
  grass7/raster/r.colors.matplotlib/r.colors.matplotlib.py
  grass7/raster/r.flowfill/r.flowfill.py
  grass7/raster/r.hypso/r.hypso.py
  grass7/raster/r.mwprecip/r.mwprecip.py
  grass7/raster/r.object.activelearning/r.object.activelearning.py
  grass7/raster/r.richdem.breachdepressions/r.richdem.breachdepressions.py
  grass7/raster/r.richdem.filldepressions/r.richdem.filldepressions.py
  grass7/raster/r.richdem.flowaccumulation/r.richdem.flowaccumulation.py
  grass7/raster/r.richdem.resolveflats/r.richdem.resolveflats.py
  grass7/raster/r.richdem.terrainattribute/r.richdem.terrainattribute.py
  grass7/raster/r.width.funct/r.width.funct.py
  grass7/vector/v.faultdirections/v.faultdirections.py
  grass7/vector/v.in.pygbif/v.in.pygbif.py
  grass7/vector/v.stream.profiler/v.stream.profiler.py
Labels: enhancement

#234 r.diversity: open config file in non-bytes mode
  grass7/raster/r.diversity/r.diversity.py
Labels: bug
