Repository OSGeo/grass-addons, pull requests merged in 2020-10, with the labels that each got.

#312 i.ortho.corr: replace os2emxpath
  grass7/imagery/i.ortho.corr/i.ortho.corr.py
Labels: bug

#314 v.class.ml: fix compile module on OS MS Windows platform
  grass7/vector/v.class.ml/v.class.ml.py
Labels: addons, bug

#307 tools/cronjobs_osgeo_lxd: fix Add-On src and commits url in the manual html page
  tools/cronjobs_osgeo_lxd/check_addons_urls.sh
  tools/cronjobs_osgeo_lxd/compile_addons_git.sh
  tools/cronjobs_osgeo_lxd/cron_grass78_releasebranch_78_build_bins.sh
Labels: manual

#319 tools/compile_addons_git.sh: call explicitly with bash
  tools/cronjobs_osgeo_lxd/compile_addons_git.sh
Labels: bug

#322 i.sentinel.download: enable footprint saving for Sentinel-1 data
  grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py
Labels: bug

#324 r.learn.ml: fix deprecated joblib import
  grass7/raster/r.learn.ml/r.learn.ml.py
Labels: bug
