Repository OSGeo/grass-addons, pull requests merged in 2021-01, with the labels that each got.

#384 v.in.pygbif: fix lazy import of 'osgeo' module
  grass7/vector/v.in.pygbif/v.in.pygbif.py
Labels: Windows, bug

#387 r.out.kde: fix lazy import of 'PIL' module
  grass7/raster/r.out.kde/r.out.kde.py
Labels: Windows, bug

#385 v.in.redlist: fix lazy import of 'osgeo' module
  grass7/vector/v.in.redlist/v.in.redlist.py
Labels: Windows, bug

#386 r.object.activelearning: fix lazy import of 'scipy', 'numpy' module
  grass7/raster/r.object.activelearning/r.object.activelearning.py
Labels: Windows, bug

#394 v.vect.stats.multi: Add example with column names
  grass7/vector/v.vect.stats.multi/v.vect.stats.multi.html
Labels: manual

#362 v.in.csv: Easy import of CSV as vector points
  grass7/vector/v.in.csv/Makefile
  grass7/vector/v.in.csv/v.in.csv.html
  grass7/vector/v.in.csv/v.in.csv.py
Labels: new addon

#361 m.csv.clean: Cleaning of CSV files
  grass7/misc/m.csv.clean/Makefile
  grass7/misc/m.csv.clean/m.csv.clean.html
  grass7/misc/m.csv.clean/m.csv.clean.py
Labels: new addon

#398 wx.metadata: check dependencies with Python3
  grass7/gui/wxpython/wx.metadata/Makefile
Labels: bug

#402 wxGUI/wx.metadata: lazy import of non standard py modules
  grass7/gui/wxpython/wx.metadata/config/init_md.txt
  grass7/gui/wxpython/wx.metadata/db.csw.admin/db.csw.admin.py
  grass7/gui/wxpython/wx.metadata/db.csw.harvest/db.csw.harvest.py
  grass7/gui/wxpython/wx.metadata/db.csw.run/db.csw.run.py
  grass7/gui/wxpython/wx.metadata/g.gui.cswbrowser/g.gui.cswbrowser.py
  grass7/gui/wxpython/wx.metadata/g.gui.metadata/g.gui.metadata.py
  grass7/gui/wxpython/wx.metadata/m.csw.update/m.csw.update.py
  grass7/gui/wxpython/wx.metadata/mdlib/Makefile
  grass7/gui/wxpython/wx.metadata/mdlib/cswlib.py
  grass7/gui/wxpython/wx.metadata/mdlib/cswutil.py
  grass7/gui/wxpython/wx.metadata/mdlib/dependency.py
  grass7/gui/wxpython/wx.metadata/mdlib/mdeditorfactory.py
  grass7/gui/wxpython/wx.metadata/mdlib/mdgrass.py
  grass7/gui/wxpython/wx.metadata/mdlib/mdjinjaparser.py
  grass7/gui/wxpython/wx.metadata/mdlib/mdpdffactory.py
  grass7/gui/wxpython/wx.metadata/mdlib/mdpdftheme.py
  grass7/gui/wxpython/wx.metadata/mdlib/mdutil.py
  grass7/gui/wxpython/wx.metadata/r.info.iso/r.info.iso.py
  grass7/gui/wxpython/wx.metadata/t.info.iso/t.info.iso.py
  grass7/gui/wxpython/wx.metadata/v.info.iso/v.info.iso.py
Labels: GUI, bug

#405 i.modis.download: fix error message when settings file not found
  grass7/imagery/i.modis/i.modis.download/i.modis.download.py
Labels: enhancement

#404 i.modis.import: misleading error message (pymodis is not installed)
  grass7/imagery/i.modis/i.modis.import/i.modis.import.py
Labels: enhancement

#409 r.confusionmatrix: Support usage of a single class in reference
  grass7/raster/r.confusionmatrix/r.confusionmatrix.py
  grass7/raster/r.confusionmatrix/testsuite/data/confusionmatrix_raster_matrix.csv
  grass7/raster/r.confusionmatrix/testsuite/data/confusionmatrix_raster_matrix_oneclass.csv
  grass7/raster/r.confusionmatrix/testsuite/test_r_confusionmatrix.py
Labels: enhancement
