Repository OSGeo/grass-addons, pull requests merged in 2021-07, with the labels that each got.

#576 r.suitability.regions: New addon for suitability scores
  src/raster/r.suitability.regions/Makefile
  src/raster/r.suitability.regions/option01.png
  src/raster/r.suitability.regions/option02.png
  src/raster/r.suitability.regions/option03.png
  src/raster/r.suitability.regions/option04.png
  src/raster/r.suitability.regions/option05.png
  src/raster/r.suitability.regions/r.suitability.regions.html
  src/raster/r.suitability.regions/r.suitability.regions.py
Labels: new addon

#586 g.download.location: Add path option for compatibility with core module
  src/general/g.download.location/g.download.location.py
Labels: enhancement

#591 CI: Install g.download.location only if needed
  .github/workflows/test.sh
Labels: CI
