Repository OSGeo/grass-addons, pull requests merged in 2021-06, with the labels that each got.

#543 Add g.projpicker
  grass7/general/g.projpicker/Makefile
  grass7/general/g.projpicker/g.projpicker.html
  grass7/general/g.projpicker/g.projpicker.py
Labels: enhancement, new addon

#547 i.modis manual: add missing products
  grass7/imagery/i.modis/i.modis.html
Labels: manual

#549 i.modis.download: more reasonable error handling
  grass7/imagery/i.modis/i.modis.download/i.modis.download.html
  grass7/imagery/i.modis/i.modis.download/i.modis.download.py
  grass7/imagery/i.modis/i.modis.html
  grass7/imagery/i.modis/i.modis.import/i.modis.import.html
Labels: bug

#550 r.extract: fix AttributeError 'append_random'
  grass7/raster/r.extract/r.extract.py
Labels: bug, help wanted

#545 Add i.gabor
  grass7/imagery/i.gabor/Makefile
  grass7/imagery/i.gabor/i.gabor.html
  grass7/imagery/i.gabor/i.gabor.py
  grass7/imagery/i.gabor/i_gabor_imaginary.png
  grass7/imagery/i.gabor/i_gabor_individual.png
  grass7/imagery/i.gabor/i_gabor_ortho.png
  grass7/imagery/i.gabor/i_gabor_quant.png
  grass7/imagery/i.gabor/i_gabor_segment.png
Labels: enhancement, new addon

#524 Fix compilation of addon manuals for Windows
  grass7/general/g.isis3mt/g.isis3mt.py
  grass7/imagery/i.ann.maskrcnn/i.ann.maskrcnn.detect/i.ann.maskrcnn.detect.py
  grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py
  grass7/raster/r.connectivity/r.connectivity.distance/r.connectivity.distance.py
  grass7/raster/r.flowfill/r.flowfill.py
  grass7/raster/r.learn.ml2/r.learn.train/r.learn.train.py
Labels: Windows

#556 v.rast.bufferstats: add tests
  grass7/vector/v.rast.bufferstats/testsuite/test_v_rast_bufferstats.py
  grass7/vector/v.rast.bufferstats/v.rast.bufferstats.py
Labels: bug

#570 t.info.iso manual: minimal content added
  grass7/gui/wxpython/wx.metadata/t.info.iso/t.info.iso.html
  grass7/gui/wxpython/wx.metadata/t.info.iso/t.info.iso.py
Labels: manual
