Repository OSGeo/grass-addons, pull requests merged in 2021-02, with the labels that each got.

#414 r.extract: new addon for extracting categories
  grass7/raster/r.extract/Makefile
  grass7/raster/r.extract/r.extract.html
  grass7/raster/r.extract/r.extract.py
  grass7/raster/r.extract/testsuite/r_extract_test.py
Labels: new addon

#416 i.sentinel.coverage: fix footprints
  grass7/imagery/i.sentinel/i.sentinel.coverage/i.sentinel.coverage.py
Labels: bug

#429 wxGUI/wx.metadata: fix retrieval of projection information (get EPSG code)
  grass7/gui/wxpython/wx.metadata/mdlib/mdgrass.py
Labels: GUI, bug

#399 GitHub action: added flake8 tests
  .github/workflows/flake8.yml
  grass7/.flake8
  grass7/gui/wxpython/.flake8
Labels: enhancement

#382 r.bearing.distance r.skyline v.percolate: added a new features
  grass7/raster/r.bearing.distance/Makefile
  grass7/raster/r.bearing.distance/azimuth.c
  grass7/raster/r.bearing.distance/azimuth.h
  grass7/raster/r.bearing.distance/file.c
  grass7/raster/r.bearing.distance/file.h
  grass7/raster/r.bearing.distance/global_vars.h
  grass7/raster/r.bearing.distance/main.c
  grass7/raster/r.bearing.distance/r.bearing.distance.html
  grass7/raster/r.bearing.distance/raster_file.c
  grass7/raster/r.bearing.distance/raster_file.h
  grass7/raster/r.skyline/Makefile
  grass7/raster/r.skyline/azimuth.c
  grass7/raster/r.skyline/azimuth.h
  grass7/raster/r.skyline/file.c
  grass7/raster/r.skyline/file.h
  grass7/raster/r.skyline/find_edges.c
  grass7/raster/r.skyline/find_edges.h
  grass7/raster/r.skyline/find_horizon.c
  grass7/raster/r.skyline/find_horizon.h
  grass7/raster/r.skyline/global_vars.h
  grass7/raster/r.skyline/list.c
  grass7/raster/r.skyline/list.h
  grass7/raster/r.skyline/main.c
  grass7/raster/r.skyline/r.skyline.html
  grass7/raster/r.skyline/raster_file.c
  grass7/raster/r.skyline/raster_file.h
  grass7/raster/r.skyline/skyline.c
  grass7/raster/r.skyline/skyline.h
  grass7/raster/r.skyline/sort.c
  grass7/raster/r.skyline/sort.h
  grass7/vector/v.percolate/Makefile
  grass7/vector/v.percolate/distance.c
  grass7/vector/v.percolate/distance.h
  grass7/vector/v.percolate/edge_array.c
  grass7/vector/v.percolate/edge_array.h
  grass7/vector/v.percolate/file.c
  grass7/vector/v.percolate/file.h
  grass7/vector/v.percolate/global_vars.h
  grass7/vector/v.percolate/groups.c
  grass7/vector/v.percolate/groups.h
  grass7/vector/v.percolate/main.c
  grass7/vector/v.percolate/node.c
  grass7/vector/v.percolate/node.h
  grass7/vector/v.percolate/percolate.c
  grass7/vector/v.percolate/percolate.h
  grass7/vector/v.percolate/v.percolate.html
  grass7/vector/v.percolate/vector.c
  grass7/vector/v.percolate/vector.h
Labels: new addon

#445 i.sentinel.coverage manual: improve examples
  grass7/imagery/i.sentinel/i.sentinel.coverage/i.sentinel.coverage.html
Labels: manual

#444 r.slope.direction: replace method with slope_measure in the manual
  grass7/raster/r.slope.direction/r.slope.direction.html
Labels: manual

#442 i.landsat.qa: qa bands from landsat collection 1and 2
  grass7/imagery/i.landsat/Makefile
  grass7/imagery/i.landsat/i.landsat.qa/Makefile
  grass7/imagery/i.landsat/i.landsat.qa/i.landsat.qa.html
  grass7/imagery/i.landsat/i.landsat.qa/i.landsat.qa.py
Labels: enhancement

#388 cronjobs: manual search form added
  tools/cronjobs_osgeo_lxd/cron_grass78_releasebranch_78_build_bins.sh
  tools/cronjobs_osgeo_lxd/cron_grass7_HEAD_build_bins.sh
Labels: manual
