Repository OSGeo/grass-addons, pull requests merged in 2021-12, with the labels that each got.

#639 v.mapcalc, v.stream.profiler: fix MODULE_TOPDIR
  src/vector/v.mapcalc/Makefile
  src/vector/v.stream.profiler/Makefile
Labels: bug

#637 fix addons broken due to GRASS 8 modules API
  src/imagery/i.sentinel/i.sentinel.coverage/i.sentinel.coverage.py
  src/raster/r.valley.bottom/r.valley.bottom.py
  src/vector/v.habitat.dem/v.habitat.dem.py
Labels: bug

#636 Update to grass8 branch in contributing and readme
  .gitignore
  CONTRIBUTING.md
  README.md
  src/imagery/i.cva/Makefile
  src/vector/v.mapcalc/Makefile
  src/vector/v.stream.profiler/Makefile
Labels: enhancement, manual

#640 CI: Test with v8.0 in grass8 branch
  .github/workflows/ci.yml
Labels: CI

#646 r.area.createweight manual: clarify installation of dependencies
  src/raster/r.area.createweight/r.area.createweight.html
  src/raster/r.area.createweight/r.area.createweight.py
  src/vector/v.area.weigh/v.area.weigh.html
Labels: MacOS, manual, backport_needed

#642 i.sentinel.download: fix footprints
  src/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py
Labels: bug, backport_needed

#647 Reduce build matrix, remove Python 3.10
  .github/workflows/ci.yml
Labels: CI

#654 utils/cronjobs_osgeo_lxd: simplify find source code and history URL
  utils/cronjobs_osgeo_lxd/check_addons_urls.sh
Labels: bug, backport_needed
