Repository OSGeo/grass-addons, pull requests merged in 2021-03, with the labels that each got.

#430 wxGUI/wx.metadata: fix lazy import of GRASS GIS wxPy 'core.gcmd' module classes
  grass7/gui/wxpython/wx.metadata/g.gui.metadata/g.gui.metadata.py
  grass7/gui/wxpython/wx.metadata/mdlib/cswlib.py
  grass7/gui/wxpython/wx.metadata/mdlib/mdeditorfactory.py
  grass7/gui/wxpython/wx.metadata/mdlib/mdjinjaparser.py
Labels: GUI, Windows, bug

#460 i.edge: add -n flag for empty input/output
  grass7/imagery/i.edge/canny.c
  grass7/imagery/i.edge/main.c
Labels: enhancement

#461 i.cutlines: use empty input support of i.edge
  grass7/imagery/i.cutlines/i.cutlines.html
  grass7/imagery/i.cutlines/i.cutlines.py
  grass7/imagery/i.cutlines/i_cutlines_canny.png
  grass7/imagery/i.cutlines/i_cutlines_default.png
Labels: bug

#464 i.landsat.download manual: more background info
  grass7/imagery/i.landsat/i.landsat.download/i.landsat.download.html
Labels: manual

#419 i.sentinel.download: add Earth Explorer as data-source for Sentinel-2 Level-1C data
  grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.html
  grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py
  grass7/imagery/i.sentinel/i.sentinel.parallel.download/i.sentinel.parallel.download.py
Labels: enhancement

#466 r3.forestfrag: Make string replace Python 3 compatible
  grass7/raster/r.forestfrag/r.forestfrag.py
  grass7/raster3d/r3.forestfrag/r3.forestfrag.py
Labels: bug

#396 r.centroids
  grass7/raster/r.centroids/Makefile
  grass7/raster/r.centroids/r.centroids.html
  grass7/raster/r.centroids/r.centroids.py
  grass7/raster/r.centroids/r_centroids_basin_50K.png
Labels: new addon

#478 i.sentinel.download: fixes for downloading using ESA-identifier
  grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py
Labels: bug

#483 i.sentinel.coverage: Exit with correct message if no products are found
  grass7/imagery/i.sentinel/i.sentinel.coverage/i.sentinel.coverage.py
Labels: bug

#436 i.nightlights.intercalibration: update to Python 3
  grass7/imagery/i.nightlights.intercalibration/intercalibration_coefficients.py
  grass7/imagery/i.nightlights.intercalibration/test_intercalibration_models.py
Labels: help wanted

#487 t.upgrade now available in GRASS core
  grass7/temporal/t.upgrade/Makefile
  grass7/temporal/t.upgrade/t.upgrade.html
  grass7/temporal/t.upgrade/t.upgrade.py
Labels: enhancement

#488 add GDAL and pygbif to extra_requirements
  .github/workflows/ci.yml
  .github/workflows/extra_requirements.txt
  grass7/vector/v.in.pygbif/v.in.pygbif.py
Labels: bug
