Repository OSGeo/grass-addons, pull requests merged in 2022-10, with the labels that each got.

#751 t.rast.patch: allow use of virtual format
  src/temporal/t.rast.patch/t.rast.patch.html
  src/temporal/t.rast.patch/t.rast.patch.py
Labels: enhancement, Python

#806 .github/workflows: fix `MODULE_TOPDIR` ENV var path value
  .github/workflows/ci.yml
Labels: bug, CI

#805 i.sentinel.parallel.download: Fix CPU count and options access
  src/imagery/i.sentinel/i.sentinel.parallel.download/i.sentinel.parallel.download.py
Labels: bug

#750 d.explanation.plot: Customize raster count, operators, fonts
  src/display/d.explanation.plot/d.explanation.plot.html
  src/display/d.explanation.plot/d.explanation.plot.py
  src/display/d.explanation.plot/d_explanation_plot_with_r_series.png
Labels: enhancement

#799 r.denoise: fix pyproj warnings (rebased to grass8)
  src/raster/r.denoise/r.denoise.py
Labels: bug

#812 t.rast.whatcsv: fix by using pygrass Module, not read_command
  src/temporal/t.rast.whatcsv/t.rast.whatcsv.py
Labels: bug

#813 CI: upgrade to latest R to fix test
  .github/workflows/ci.yml
Labels: CI

#811 Enable Python SyntaxError checks, move to Python 3
  .flake8
  pyproject.toml
  src/gui/wxpython/newgui/api_test.py
  src/gui/wxpython/newgui/frame.py
  src/gui/wxpython/newgui/gui_mapwindow.py
  src/gui/wxpython/newgui/mapwindow.py
  src/gui/wxpython/newgui/render2.py
  src/gui/wxpython/newgui/wxgui.py
  src/gui/wxpython/wx.rdigit/rdigit/main.py
  src/gui/wxpython/wx.stream/gui_modules/ImageViewer.py
  src/gui/wxpython/wx.stream/gui_modules/rstream_panelOne.py
  src/gui/wxpython/wx.wms/LoadConfig.py
  src/gui/wxpython/wx.wms/addserver.py
  src/gui/wxpython/wx.wms/parse.py
  src/gui/wxpython/wx.wms/wmsmenu.py
  src/hadoop/hd/dependency.py
  src/hadoop/hd/hd.esri2vector/hd.esri2vector.py
  src/hadoop/hd/hd.hdfs.out.vector/hd.hdfs.out.vector.py
  src/hadoop/hd/hd.hive.select/hd.hive.select.py
  src/hadoop/hd/hdfsgrass/hdfs_grass_lib.py
  src/hadoop/hd/hdfsgrass/hdfs_grass_util.py
  src/hadoop/hd/hdfswrapper/hdfs_hook.py
  src/hadoop/hd/hdfswrapper/hive_hook.py
  src/hadoop/hd/hdfswrapper/hive_table.py
  src/hadoop/hd/hdfswrapper/utils.py
  src/hadoop/hd/hdfswrapper/webhdfs_hook.py
  src/raster/r.agent/tests/test_grassland.py
Labels: bug

#804 r.in.usgs: Use parallel for patching, cache tolerance
  src/raster/r.in.usgs/r.in.usgs.py
Labels: enhancement

#810 v.db.pyupdate: fix to use latest v.db.select format=json option
  src/vector/v.db.pyupdate/testsuite/test_v_db_pyupdate.py
  src/vector/v.db.pyupdate/v.db.pyupdate.py
Labels: bug

#809 Add parallel keyword for multiprocessing and OpenMP
  src/imagery/i.segment.hierarchical/i.segment.hierarchical.py
  src/imagery/i.segment.stats/i.segment.stats.py
  src/imagery/i.segment.uspo/i.segment.uspo.py
  src/imagery/i.spec.sam/main.c
  src/raster/r.gdd/main.c
  src/raster/r.in.usgs/r.in.usgs.py
  src/raster/r.learn.ml/r.learn.ml.py
  src/raster/r.learn.ml2/r.learn.train/r.learn.train.py
  src/raster/r.massmov/main.c
  src/raster/r.maxent.lambdas/r.maxent.lambdas.py
  src/raster/r.shaded.pca/r.shaded.pca.py
  src/raster/r.sim.terrain/r.sim.terrain.py
  src/raster/r.sun.daily/r.sun.daily.py
  src/raster/r.sun.hourly/r.sun.hourly.py
  src/raster/r.survey/r.survey.py
  src/raster/r.tpi/r.tpi.py
  src/raster/r.tri/r.tri.py
  src/raster/r.vector.ruggedness/r.vector.ruggedness.py
  src/raster/r.viewshed.exposure/r.viewshed.exposure.py
  src/temporal/t.rast.null/t.rast.null.py
  src/temporal/t.rast.what.aggr/t.rast.what.aggr.py
Labels: manual

#815 r.centroids: Fix module and test
  src/raster/r.centroids/r.centroids.py
  src/raster/r.centroids/testsuite/test_r_centroids.py
  src/raster/r.sample.category/testsuite/test_numbers.sh
Labels: bug, new addon

#817 i.gabor: fix lazy import py packages
  src/imagery/i.gabor/i.gabor.py
Labels: bug

#818 cron_grass7_binaries: fix relative path in red redirect box in G78 manuals
  utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh
Labels: manual

#808 g.citation: update regex to get date and author from manual
  src/general/g.citation/g.citation.py
  src/general/g.citation/testsuite/test_g_citation.py
Labels: bug

#794 t.rast.import.netcdf: Create STRDS from netcdf-cf data
  .github/workflows/extra_requirements.txt
  src/temporal/t.rast.import.netcdf/Makefile
  src/temporal/t.rast.import.netcdf/t.rast.import.netcdf.html
  src/temporal/t.rast.import.netcdf/t.rast.import.netcdf.py
  src/temporal/t.rast.import.netcdf/testsuite/semantic_labels_invalid.conf
  src/temporal/t.rast.import.netcdf/testsuite/semantic_labels_senorge.conf
  src/temporal/t.rast.import.netcdf/testsuite/semantic_labels_sentinel2.conf
  src/temporal/t.rast.import.netcdf/testsuite/test_t_rast_import_netcdf.py
Labels: new addon, Python

#820 r.bioclim manual: update URL to Worldclim BIOCLIM
  src/raster/r.bioclim/r.bioclim.html
  src/raster/r.bioclim/r.bioclim.py
Labels: manual

#819 g.citation: fix module output parameter
  src/general/g.citation/g.citation.py
  src/general/g.citation/testsuite/test_g_citation.py
Labels: bug

#825 .github/workflows: remove build old stable GRASS GIS 8.0 version from the CI
  .github/workflows/ci.yml
Labels: CI

#826 utils/cronjobs_osgeo_lxd: copy addon HTML man page hamburger menu TOC SVG images to the addons dir
  utils/cronjobs_osgeo_lxd/cron_grass8_main_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass8_relbranch_build_binaries.sh
Labels: bug, manual

#828 SEO GRASS GIS 7 manual: properly inject canonical
  utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_job_list_grass
Labels: manual

#824 i.ann.maskrcnn: remove deprecated distutils
  src/imagery/i.ann.maskrcnn/maskrcnnlib/model.py
  src/imagery/i.ann.maskrcnn/maskrcnnlib/utils.py
Labels: bug

#829 r.series.boxplot / t.rast.boxplot: html manual fixes
  src/raster/r.series.boxplot/r.series.boxplot.html
  src/temporal/t.rast.boxplot/t.rast.boxplot.html
Labels: bug, manual
