Repository OSGeo/grass-addons, pull requests merged in 2022-06, with the labels that each got.

#761 utils/cronjobs_osgeo_lxd: fix MS Windows Addons compilation log files URL link
  utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass8_main_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass8_relbranch_build_binaries.sh
  utils/cronjobs_osgeo_lxd/grass-addons-index.sh
Labels: bug, Windows

#711 r.mapcalc.tiled: use parallelized r.patch if no overlap
  src/raster/r.mapcalc.tiled/r.mapcalc.tiled.html
  src/raster/r.mapcalc.tiled/r.mapcalc.tiled.py
Labels: enhancement

#702 r.survey: addon to calculate the solid angle subtended by an object on the view of an observer
  src/raster/r.survey/Makefile
  src/raster/r.survey/r.survey.html
  src/raster/r.survey/r.survey.py
  src/raster/r.survey/r_survey_fig_2.png
  src/raster/r.survey/r_survey_view_angle.png
Labels: new addon
