Repository OSGeo/grass-addons, pull requests merged in 2022-08, with the labels that each got.

#770 cronjobs: src tarball version bumps
  utils/cronjobs_osgeo_lxd/cron_grass8_main_src_snapshot.sh
  utils/cronjobs_osgeo_lxd/cron_grass8_relbranch_src_snapshot.sh
Labels: CI

#775 i.sentinel.import: fix unit test (capital letter)
  src/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py
Labels: bug

#774 r.learn.ml2: fix r.category call in r.learn.predict
  src/raster/r.learn.ml2/r.learn.predict/r.learn.predict.py
Labels: bug

#764 Update r.bioclim.html
  src/raster/r.bioclim/r.bioclim.html
Labels: enhancement, manual

#779 r.series.boxplot: new addon to create boxplots of series of rasters
  src/raster/r.series.boxplot/Makefile
  src/raster/r.series.boxplot/r.series.boxplot.html
  src/raster/r.series.boxplot/r.series.boxplot.py
  src/raster/r.series.boxplot/r_series_boxplot_1.png
  src/raster/r.series.boxplot/r_series_boxplot_2.png
  src/raster/r.series.boxplot/r_series_boxplot_3.png
Labels: new addon

#782 r.series.boxplot: remove errors
  src/raster/r.series.boxplot/r.series.boxplot.html
Labels: manual
