Repository OSGeo/grass-addons, pull requests merged in 2022-05, with the labels that each got.

#735 v.tin.to.rast manual: add example
  src/vector/v.tin.to.rast/v.tin.to.rast.html
  src/vector/v.tin.to.rast/v.tin.to.rast.py
Labels: manual

#743 new addon r.boxplot
  src/raster/r.boxplot/Makefile
  src/raster/r.boxplot/r.boxplot.html
  src/raster/r.boxplot/r.boxplot.py
  src/raster/r.boxplot/r_boxplot_01.png
  src/raster/r.boxplot/r_boxplot_02.png
  src/raster/r.boxplot/r_boxplot_03.png
Labels: new addon

#748 r.boxplot documentation bugfix
  src/raster/r.boxplot/r.boxplot.html
Labels: bug
