Repository OSGeo/grass-addons, pull requests merged in 2022-03, with the labels that each got.

#707 i.modis.import: remove grass version check
  src/imagery/i.modis/i.modis.import/i.modis.import.py
Labels: bug

#710 i.sentinel.import: less obscure error message
  src/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py
Labels: Python, backport_needed

#713 i.fusion.hpf: fix "Illegal filename <.hpf>" warning
  src/imagery/i.fusion.hpf/i.fusion.hpf.py
Labels: bug, backport_needed

#708 r.viewshed.exposure: New addon to compute visual exposure
  src/raster/r.viewshed.exposure/Makefile
  src/raster/r.viewshed.exposure/r.viewshed.exposure.html
  src/raster/r.viewshed.exposure/r.viewshed.exposure.py
  src/raster/r.viewshed.exposure/r_viewshed_exposure_example_binary.png
  src/raster/r.viewshed.exposure/r_viewshed_exposure_example_solid_angle.png
  src/raster/r.viewshed.exposure/r_viewshed_exposure_workflow.png
  src/raster/r.viewshed.exposure/testsuite/test_r_viewshed_exposure.py
  src/raster/r.viewshed.exposure/validation/validate_r_viewshed_exposure.py
  src/raster/r.viewshed.exposure/validation/validation_profiling.csv
Labels: new addon

#718 G78 cronjobs: add "new version G8" box into man pages
  utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh
  utils/cronjobs_osgeo_lxd/grass-addons-index.sh
Labels: manual

#720 r.viewshed.exposure: Version for GRASS 7
  src/raster/r.viewshed.exposure/Makefile
  src/raster/r.viewshed.exposure/r.viewshed.exposure.html
  src/raster/r.viewshed.exposure/r.viewshed.exposure.py
  src/raster/r.viewshed.exposure/r_viewshed_exposure_example_binary.png
  src/raster/r.viewshed.exposure/r_viewshed_exposure_example_solid_angle.png
  src/raster/r.viewshed.exposure/r_viewshed_exposure_workflow.png
  src/raster/r.viewshed.exposure/testsuite/test_r_viewshed_exposure.py
Labels: new addon

#722 r.random.weight: fix string.replace bug
  src/raster/r.random.weight/r.random.weight.py
Labels: bug

#724 manual: g.bands has been renamed to i.band.library
  src/imagery/i.landsat/i.landsat.import/i.landsat.import.html
  src/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.html
Labels: manual
