Repository OSGeo/grass-addons, pull requests merged in 2022-04, with the labels that each got.

#728 v.in.redlist: exporting text file of list of species
  src/vector/v.in.redlist/v.in.redlist.py
Labels: bug, backport_needed

#730 r.viewshed.exposure manual: fix HTML
  src/raster/r.viewshed.exposure/r.viewshed.exposure.html
Labels: bug

#731 G78 addon cronjob: add "new version G8" box into addon man pages
  utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh
Labels: manual

#733 r.euro.ecosystem manual: fix HTML tag
  src/raster/r.euro.ecosystem/r.euro.ecosystem.html
Labels: bug, backport_needed

#736 v.fixed.segmentpoints manual: fix broken HTML
  src/vector/v.fixed.segmentpoints/v.fixed.segmentpoints.html
Labels: bug, manual

#734 G78 addon cronjob: update "new version G8" box
  utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh
Labels: manual

#738 r.catchment: read stdout as text, Python 3 update
  src/raster/r.catchment/r.catchment.py
Labels: bug

#737 cron_grass8_main_build_binaries.sh: no longer generate i18N .pot files
  utils/cronjobs_osgeo_lxd/cron_grass8_main_build_binaries.sh
Labels: bug

#732 v.stream.profiler: try-except for matplotlib import
  src/vector/v.stream.profiler/v.stream.profiler.py
Labels: backport_needed

#742 CI: Add v8.2 branch to test build and test run
  .github/workflows/ci.yml
Labels: CI
