Repository OSGeo/grass-addons, pull requests merged in 2022-01, with the labels that each got.

#656 utils/cronjobs_osgeo_lxd: generate addons modules.xml file on osgeo lxd container server
  utils/cronjobs_osgeo_lxd/README.md
  utils/cronjobs_osgeo_lxd/build-xml.py
  utils/cronjobs_osgeo_lxd/compile_addons_git.sh
  utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass8_relbranch_build_binaries.sh
Labels: enhancement, backport_needed

#658 r.connectivity.*: Spelling fixes
  src/raster/r.connectivity/r.connectivity.corridors/r.connectivity.corridors.html
  src/raster/r.connectivity/r.connectivity.corridors/r.connectivity.corridors.py
  src/raster/r.connectivity/r.connectivity.distance/r.connectivity.distance.html
  src/raster/r.connectivity/r.connectivity.distance/r.connectivity.distance.py
  src/raster/r.connectivity/r.connectivity.network/r.connectivity.network.html
  src/raster/r.connectivity/r.connectivity.network/r.connectivity.network.py
Labels: manual

#659 r.connectivity.corridors: Use default number of files limit
  src/raster/r.connectivity/r.connectivity.corridors/r.connectivity.corridors.py
Labels: backport_needed

#666 CI: Fix names of checkout steps for core and addons inversion
  .github/workflows/ci.yml
Labels: bug, CI

#667 Update of grass7 leftovers to grass8 or version generalization
  src/general/g.cloud/cloud_collect.sh
  src/general/g.cloud/cloud_unpack.py
  src/general/g.cloud/g.cloud.html
  src/general/g.cloud/g.cloud.py
  src/general/g.cloud/test/launch_SGE_grassjob.sh
  src/gui/wxpython/wx.wms/readme.txt
  src/imagery/i.gabor/i.gabor.html
  src/imagery/i.landsat/i.landsat.html
  src/imagery/i.modis/i.modis.download/i.modis.download.html
  src/imagery/i.modis/i.modis.html
  src/imagery/i.spec.sam/test1.sh
  src/raster/r.diversity/r.diversity.py
  src/raster/r.futures/r.futures.calib/r.futures.calib.html
  src/raster/r.futures/r.futures.demand/r.futures.demand.html
  src/raster/r.futures/r.futures.devpressure/r.futures.devpressure.html
  src/raster/r.futures/r.futures.html
  src/raster/r.futures/r.futures.parallelpga/r.futures.parallelpga.html
  src/raster/r.futures/r.futures.potential/r.futures.potential.html
  src/raster/r.futures/r.futures.potsurface/r.futures.potsurface.html
  src/raster/r.green/r.green.hydro/r.green.hydro.financial/r.green.hydro.financial.html
  src/raster/r.mblend/README.md
  src/raster/r.object.spatialautocor/r.object.spatialautocor.html
  src/raster/r.pops.spread/CITATION.cff
  src/raster/r.pops.spread/pops-core/CITATION.cff
  src/raster/r.soils.texture/r.soils.texture.html
  src/raster/r.stream.variables/r.stream.variables.sh
  src/raster/r.stream.watersheds/r.stream.watersheds.sh
  src/raster/r.suitability.regions/r.suitability.regions.html
  src/tools/mk_isis_menu.README
  src/tools/mk_isis_menu.sh
  src/vector/v.class.ml/v.class.ml.html
  src/vector/v.habitat.dem/v.habitat.dem.html
Labels: bug

#676 roadmap: move folder to promo repo
  roadmap/README
  roadmap/grass_roadmap.svg
  roadmap/grass_web_evolution/baylor_09_1999.png
  roadmap/grass_web_evolution/cerl_05_1998.png
  roadmap/grass_web_evolution/grass2_0_1987_cmd.png
  roadmap/grass_web_evolution/grass2_0_1987_gui.png
  roadmap/grass_web_evolution/grass_osgeo_11_2012_newsite.png
  roadmap/grass_web_evolution/grass_osgeo_org_5_2012.png
  roadmap/grass_web_evolution/iln_05_1997.png
  roadmap/grass_web_evolution/index.html
  roadmap/grass_web_evolution/itc_01_2002a.png
  roadmap/grass_web_evolution/itc_05_2002b.png
  roadmap/grass_web_evolution/itc_08_2001b.png
  roadmap/grass_web_evolution/osgeo_01_2009.png
  roadmap/grass_web_evolution/phygeo_08_1999.png
  roadmap/grass_web_evolution/phygeo_08_2000a.png
  roadmap/grass_web_evolution/phygeo_08_2000b.png
  roadmap/grass_web_evolution/phygeo_08_2001a.png
  roadmap/grass_web_evolution/phygeo_08_2001b.png
  roadmap/grass_web_evolution/thumbs/baylor_09_1999.png
  roadmap/grass_web_evolution/thumbs/cerl_05_1998.png
  roadmap/grass_web_evolution/thumbs/grass_osgeo_11_2012_newsite.png
  roadmap/grass_web_evolution/thumbs/grass_osgeo_org_5_2012.png
  roadmap/grass_web_evolution/thumbs/iln_05_1997.png
  roadmap/grass_web_evolution/thumbs/itc_01_2002a.png
  roadmap/grass_web_evolution/thumbs/itc_05_2002b.png
  roadmap/grass_web_evolution/thumbs/itc_08_2001b.png
  roadmap/grass_web_evolution/thumbs/phygeo_08_1999.png
  roadmap/grass_web_evolution/thumbs/phygeo_08_2000a.png
  roadmap/grass_web_evolution/thumbs/phygeo_08_2000b.png
  roadmap/grass_web_evolution/thumbs/phygeo_08_2001a.png
  roadmap/grass_web_evolution/thumbs/phygeo_08_2001b.png
  roadmap/gui/Wxgui-atm0-gnulinux.png
  roadmap/gui/dm.png
  roadmap/gui/gism.png
  roadmap/gui/grass4-login.png
  roadmap/gui/qgis08_grass6_toolbox.png
  roadmap/gui/tcltkgrass.png
  roadmap/other/codehistory.png
  roadmap/other/codehistory2.png
  roadmap/other/grasslogo_vector.svg
  roadmap/vdigit/vdigit-text.png
  roadmap/vdigit/vdigit6.png
  roadmap/vdigit/wxgrass_digit-03.png
Labels: manual

#678 r.in.nasadem: fix name 'srid' is not defined
  src/raster/r.in.nasadem/r.in.nasadem.py
Labels: backport_needed

#670 Drop outdated utils/addons/ compile scripts
  utils/addons/README.txt
  utils/addons/build-xml.py
  utils/addons/compile-addons.sh
  utils/addons/compile-grass.sh
  utils/addons/compile-xml.sh
  utils/addons/compile.sh
  utils/addons/crontab.build
  utils/addons/crontab.publish
  utils/addons/get_page_description.py
  utils/addons/grass-addons-build.sh
  utils/addons/grass-addons-index.sh
  utils/addons/grass-addons-publish.sh
  utils/addons/test/data/g.almost.empty.html
  utils/addons/test/data/g.broken.example.html
  utils/addons/test/data/g.no.keywords.html
  utils/addons/test/data/r.group.page.html
  utils/addons/test/data/r.group.page.with.toc.html
  utils/addons/test/data/r.standard.example.html
  utils/addons/test/data/wxGUI.example.html
  utils/addons/test/test_description_extraction.sh
  utils/addons/update_manual.py
Labels: backport_needed

#663 new addon v.what.rast.label
  src/vector/v.what.rast.label/Makefile
  src/vector/v.what.rast.label/v.what.rast.label.html
  src/vector/v.what.rast.label/v.what.rast.label.py
Labels: new addon

#661 v.to.rast.multi: create raster maps for multiple attributes of a vector map
  src/vector/v.to.rast.multi/Makefile
  src/vector/v.to.rast.multi/testsuite/test_rasterize_multi.py
  src/vector/v.to.rast.multi/v.to.rast.multi.html
  src/vector/v.to.rast.multi/v.to.rast.multi.py
Labels: new addon, Python, backport_needed

#680 r.maxent.lambdas: Port to Python
  src/raster/r.maxent.lambdas/Makefile
  src/raster/r.maxent.lambdas/r.maxent.lambdas.html
  src/raster/r.maxent.lambdas/r.maxent.lambdas.py
  src/raster/r.maxent.lambdas/r.maxent.lambdas.sh
Labels: Python, backport_needed

#681 r.out.maxent_swd: update to GRASS 7/8 and Python 3
  src/raster/r.out.maxent_swd/Makefile
  src/raster/r.out.maxent_swd/r.out.maxent_swd.html
  src/raster/r.out.maxent_swd/r.out.maxent_swd.py
Labels: Python, backport_needed

#669 utils/cronjobs_osgeo_lxd: fix G7/G8 addons manual page source code and history URL git branch
  utils/cronjobs_osgeo_lxd/compile_addons_git.sh
  utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass8_relbranch_build_binaries.sh
Labels: bug, manual

#610 i.sentinel.import: write semantic label with r.support
  src/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py
Labels: enhancement

#686 r.colors.out_sld: check if input map exists
  src/raster/r.colors.out_sld/r.colors.out_sld.py
Labels: bug, Python, backport_needed
