Repository OSGeo/grass-addons, pull requests merged in 2022-02, with the labels that each got.

#694 r.forcircular: Evaluation of circular bioconomy level of forest ecosystems
  src/raster/r.forcircular/Makefile
  src/raster/r.forcircular/avoided_emission.png
  src/raster/r.forcircular/dip.png
  src/raster/r.forcircular/parcel.png
  src/raster/r.forcircular/r.forcircular.html
  src/raster/r.forcircular/r.forcircular.py
  src/raster/r.forcircular/stumpage.png
  src/raster/r.forcircular/stumpage_function.png
  src/raster/r.forcircular/tech_function.png
Labels: new addon

#695 r.forcircular: Evaluation of circular bioconomy level of forest ecosystems (GRASS GIS 7 version)
  src/raster/r.forcircular/Makefile
  src/raster/r.forcircular/avoided_emission.png
  src/raster/r.forcircular/dip.png
  src/raster/r.forcircular/parcel.png
  src/raster/r.forcircular/r.forcircular.html
  src/raster/r.forcircular/r.forcircular.py
  src/raster/r.forcircular/stumpage.png
  src/raster/r.forcircular/stumpage_function.png
  src/raster/r.forcircular/tech_function.png
Labels: new addon, Python

#688 r.colors.out_sld: add percent counter
  src/raster/r.colors.out_sld/r.colors.out_sld.py
Labels: Python

#701 v.what.rast.label manual: minor reformulation
  src/vector/v.what.rast.label/v.what.rast.label.html
Labels: manual

#705 i.sentinel.import fails on Windows with Invalid format string
  src/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py
Labels: Windows

#706 i.sentinel.import: os.linesep -> \n
  src/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py
Labels: Windows
