Repository OSGeo/grass-addons, pull requests merged in 2022-09, with the labels that each got.

#787 r.mapcalc.tiled: fix not change MAPSET search path
  src/raster/r.mapcalc.tiled/r.mapcalc.tiled.py
Labels: bug

#789 i.modis.download manual: expand USGS app authorization
  src/imagery/i.modis/i.modis.download/i.modis.download.html
Labels: manual

#780 utils/cronjobs_osgeo_lxd: allow register all addons keywords in main Keywords Index
  utils/cronjobs_osgeo_lxd/cron_grass8_main_build_binaries.sh
Labels: enhancement, manual

#792 utils/cronjobs_osgeo_lxd: allow register all addons keywords in main Keywords Index
  utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass8_relbranch_build_binaries.sh
Labels: enhancement, manual

#781 t.rast.boxplot: new addon to create boxplots of rasters in a strds
  src/temporal/t.rast.boxplot/Makefile
  src/temporal/t.rast.boxplot/t.rast.boxplot.html
  src/temporal/t.rast.boxplot/t.rast.boxplot.py
  src/temporal/t.rast.boxplot/t_rast_boxplot_01.png
  src/temporal/t.rast.boxplot/t_rast_boxplot_02.png
  src/temporal/t.rast.boxplot/t_rast_boxplot_03.png
  src/temporal/t.rast.boxplot/t_rast_boxplot_04.png
Labels: new addon

#795 m.crawl.thredds: New module to list netcdf datasets on a Thredds Data Server (TDS)
  src/misc/m.crawl.thredds/Makefile
  src/misc/m.crawl.thredds/m.crawl.thredds.html
  src/misc/m.crawl.thredds/m.crawl.thredds.py
  src/misc/m.crawl.thredds/testsuite/test_m_crawl_thredds.py
Labels: new addon, Python

#800 SEO: define canonical URL in older manual pages; robots.txt tweaks
  utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass8_main_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass8_relbranch_build_binaries.sh
  utils/cronjobs_osgeo_lxd/robots.txt
Labels: manual

#801 SEO: define canonical URL in older addon and libpython manuals
  utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh
Labels: manual
