Repository OSGeo/grass-addons, pull requests merged in 2023-11, with the labels that each got.

#973 r.random.walk: fix importlib issue
  src/raster/r.random.walk/testsuite/test_r_random_walk.py
Labels: bug, Python

#967 v.kriging: Fix a segmentation fault
  src/vector/v.kriging/main.c
Labels: bug

#980 v.rast.move: Add missing keywords
  src/vector/v.rast.move/v.rast.move.py
Labels: Python

#985 i.sentinel.download: add S3SL1RBT productype
  src/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.html
  src/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py
Labels: enhancement, Python
