Repository OSGeo/grass-addons, pull requests merged in 2023-05, with the labels that each got.

#893 wx.metadata: use osmsm map static OpenStreetMap image generator
  src/gui/wxpython/wx.metadata/mdlib/dependency.py
  src/gui/wxpython/wx.metadata/mdlib/mdpdffactory.py
Labels: bug, GUI, backport_needed

#895 utils/cronjobs_osgeo_lxd: compile addons without use GitHub REST API
  utils/cronjobs_osgeo_lxd/compile_addons_git.sh
Labels: enhancement

#902 docs: keyword and minor documentation fixes
  src/misc/m.printws/m.printws.py
  src/raster/r.agent/r.agent.rand/r.agent.rand.html
  src/raster/r.object.spatialautocor/r.object.spatialautocor.py
Labels: manual

#903 cronjobs: various fixes and cleanup
  utils/cronjobs_osgeo_lxd/cron_grass_legacy_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_legacy_src_snapshot.sh
  utils/cronjobs_osgeo_lxd/cron_grass_new_current_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_new_current_src_snapshot.sh
  utils/cronjobs_osgeo_lxd/cron_grass_old_current_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_old_current_src_snapshot.sh
  utils/cronjobs_osgeo_lxd/cron_grass_preview_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_preview_src_snapshot.sh
Labels: bug
