Repository OSGeo/grass-addons, pull requests merged in 2023-02, with the labels that each got.

#865 i.sentinel.download: add S3OL1 product types
  src/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.html
  src/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py
Labels: bug, enhancement, Python

#869 r.learn.train: use formatted string
  src/raster/r.learn.ml2/r.learn.predict/r.learn.predict.py
  src/raster/r.learn.ml2/r.learn.train/r.learn.train.py
Labels: bug, Python

#860 docs: update submitting guideline url
  CONTRIBUTING.md
  SUBMITTING
Labels: manual
