Repository OSGeo/grass-addons, pull requests merged in 2023-12, with the labels that each got.

#984 d.vect.scatter: new addon to create scatterplots from vector data
  src/display/d.vect.scatter/Makefile
  src/display/d.vect.scatter/d.vect.scatter.html
  src/display/d.vect.scatter/d.vect.scatter.py
  src/display/d.vect.scatter/d_vect_scatter_01.png
  src/display/d.vect.scatter/d_vect_scatter_02.png
Labels: new addon

#992 v.scatterplot: add option for dot color and size
  src/vector/v.scatterplot/v.scatterplot.html
  src/vector/v.scatterplot/v.scatterplot.py
  src/vector/v.scatterplot/v_scatterplot_01.png
  src/vector/v.scatterplot/v_scatterplot_02.png
  src/vector/v.scatterplot/v_scatterplot_03.png
Labels: enhancement

#989 cronjobs: build programmer's manual for "preview" version
  utils/cronjobs_osgeo_lxd/cron_grass_legacy_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_new_current_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_old_current_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_preview_build_binaries.sh
Labels: bug, manual

#994 cronjobs: remove outdated liblas support
  utils/cronjobs_osgeo_lxd/cron_grass_legacy_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_new_current_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_old_current_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_preview_build_binaries.sh
Labels: CI

#996 v.scatterplot: added option to draw confidence ellipses
  src/vector/v.scatterplot/v.scatterplot.html
  src/vector/v.scatterplot/v.scatterplot.py
  src/vector/v.scatterplot/v_scatterplot_04.png
Labels: enhancement

#1004 i.histo.match: add testsuite
  src/imagery/i.histo.match/testsuite/test_i_histo_match.py
Labels: enhancement, CI, Python
