Repository OSGeo/grass-addons, pull requests merged in 2023-09, with the labels that each got.

#938 i.modis.download: remove a call of non-existent function raw_input()
  src/imagery/i.modis/i.modis.download/i.modis.download.py
Labels: bug, Python

#937 i.landsat.download: remove a call of non-existent function raw_input()
  src/imagery/i.landsat/i.landsat.download/i.landsat.download.py
Labels: bug, Python

#940 r.pi manual: completion of submodule list and HTML fixes
  src/raster/r.pi/r.pi.corearea/main.c
  src/raster/r.pi/r.pi.corr.mw/main.c
  src/raster/r.pi/r.pi.csr.mw/main.c
  src/raster/r.pi/r.pi.energy.pr/main.c
  src/raster/r.pi/r.pi.energy/main.c
  src/raster/r.pi/r.pi.enn.pr/main.c
  src/raster/r.pi/r.pi.enn/main.c
  src/raster/r.pi/r.pi.export/main.c
  src/raster/r.pi/r.pi.fnn/main.c
  src/raster/r.pi/r.pi.graph.dec/main.c
  src/raster/r.pi/r.pi.graph.pr/main.c
  src/raster/r.pi/r.pi.graph.red/main.c
  src/raster/r.pi/r.pi.graph/main.c
  src/raster/r.pi/r.pi.grow/main.c
  src/raster/r.pi/r.pi.html
  src/raster/r.pi/r.pi.import/main.c
  src/raster/r.pi/r.pi.index/main.c
  src/raster/r.pi/r.pi.lm/main.c
  src/raster/r.pi/r.pi.neigh/main.c
  src/raster/r.pi/r.pi.nlm.circ/main.c
  src/raster/r.pi/r.pi.nlm.stats/main.c
  src/raster/r.pi/r.pi.nlm/main.c
  src/raster/r.pi/r.pi.odc/main.c
  src/raster/r.pi/r.pi.prob.mw/main.c
  src/raster/r.pi/r.pi.prox/main.c
  src/raster/r.pi/r.pi.rectangle/main.c
  src/raster/r.pi/r.pi.searchtime.mw/main.c
  src/raster/r.pi/r.pi.searchtime.pr/main.c
  src/raster/r.pi/r.pi.searchtime/main.c
Labels: manual

#944 r.learn.ml2: change max_features=auto to sqrt
  src/raster/r.learn.ml2/r.learn.train/r.learn.train.py
Labels: bug

#844 m.download.tnm: Add a new module for downloading The National Map (TNM) data
  src/misc/m.download.tnm/Makefile
  src/misc/m.download.tnm/m.download.tnm.html
  src/misc/m.download.tnm/m.download.tnm.py
Labels: new addon

#931 r.fuzzy.set: correction of sshape formula in fuzzy.c
  src/raster/r.fuzzy.set/fuzzy.c
  src/raster/r.fuzzy.set/r.fuzzy.set.html
Labels: bug
