Repository OSGeo/grass-addons, pull requests merged in 2023-10, with the labels that each got.

#951 cronjob: manual: inject new version box
  utils/cronjobs_osgeo_lxd/cron_grass_old_current_build_binaries.sh
Labels: manual

#954 r.flowaccumulation: Add a new addon that implements the Memory-Efficient Flow Accumulation parallel algorithm (Cho 2023)
  src/raster/r.flowaccumulation/Makefile
  src/raster/r.flowaccumulation/accumulate.c
  src/raster/r.flowaccumulation/gettimeofday.c
  src/raster/r.flowaccumulation/global.h
  src/raster/r.flowaccumulation/main.c
  src/raster/r.flowaccumulation/r.flowaccumulation.html
  src/raster/r.flowaccumulation/r_flowaccumulation_formats.png
  src/raster/r.flowaccumulation/r_flowaccumulation_nc_comparison.png
  src/raster/r.flowaccumulation/r_flowaccumulation_nc_example.png
  src/raster/r.flowaccumulation/r_flowaccumulation_r_watershed_nc_example.png
  src/raster/r.flowaccumulation/timeval_diff.c
Labels: new addon, C

#958 r.flowaccumulation: Rename flowaccumulation_diff to flow_accum_diff in the manual
  src/raster/r.flowaccumulation/r.flowaccumulation.html
Labels: manual

#959 r.accumulate: Update the manual with a new difference map name and LFP citations
  src/raster/r.accumulate/r.accumulate.html
Labels: manual

#963 m.cdo.download: Add a new addon for downloading NCEI (previouly NCDC) Climate Data Online (CDO)
  src/misc/m.cdo.download/Makefile
  src/misc/m.cdo.download/m.cdo.download.html
  src/misc/m.cdo.download/m.cdo.download.py
  src/misc/m.cdo.download/m_cdo_download_cdo_stations.png
Labels: new addon

#969 t.rast.import.netcdf: better version_check and naming
  src/temporal/t.rast.import.netcdf/t.rast.import.netcdf.py
Labels: bug

#970 m.crawl.thredds: linting and add line break at end of file
  .github/workflows/extra_requirements.txt
  src/misc/m.crawl.thredds/m.crawl.thredds.py
Labels: bug

#972 v.in.pygbif: fix identifiers
  src/vector/v.in.pygbif/v.in.pygbif.py
Labels: bug

#974 r.tpi use 'int' instead of np.int; add test
  src/raster/r.tpi/r.tpi.py
  src/raster/r.tpi/testsuite/test_tpi.py
Labels: Python

#971 t.rast.import.netcdf: fix failing tests
  src/temporal/t.rast.import.netcdf/testsuite/data/semantic_labels_invalid.conf
  src/temporal/t.rast.import.netcdf/testsuite/data/semantic_labels_senorge.conf
  src/temporal/t.rast.import.netcdf/testsuite/data/semantic_labels_sentinel2.conf
  src/temporal/t.rast.import.netcdf/testsuite/test_t_rast_import_netcdf.py
Labels: bug
