Repository OSGeo/grass-addons, pull requests merged in 2023-06, with the labels that each got.

#909 r.forcircular: fix non-HTML chars
  src/raster/r.forcircular/r.forcircular.html
Labels: manual

#606 r.random.walk
  src/raster/r.random.walk/Makefile
  src/raster/r.random.walk/r.random.walk.html
  src/raster/r.random.walk/r.random.walk.py
  src/raster/r.random.walk/r_random_walk_example.png
  src/raster/r.random.walk/r_random_walk_example_2.png
  src/raster/r.random.walk/random_walk_output.png
  src/raster/r.random.walk/testsuite/test_r_random_walk.py
Labels: new addon

#882 t.rast.climatologies: new addon to calculate climatologies
  src/temporal/t.rast.climatologies/Makefile
  src/temporal/t.rast.climatologies/t.rast.climatologies.html
  src/temporal/t.rast.climatologies/t.rast.climatologies.py
  src/temporal/t.rast.climatologies/testsuite/test_climatologies_daily.py
  src/temporal/t.rast.climatologies/testsuite/test_climatologies_monthly.py
Labels: new addon

#917 unittest: fix assertEquals() removed from python 3.12
  src/raster/r.learn.ml2/testsuite/test_gridsearch.py
Labels: bug, Python

#922 t.rast.import.netcdf: correct orientation of warped VRT files
  src/temporal/t.rast.import.netcdf/t.rast.import.netcdf.py
Labels: bug

#923 i.pysptools.unmix: fix wrong numpy dtype handling
  src/imagery/i.pysptools.unmix/i.pysptools.unmix.py
Labels: bug, Python
