Repository OSGeo/grass-addons, pull requests merged in 2023-07, with the labels that each got.

#924 wx.metadata: lazy import owslib so pre-compiling for MS Windows succeeds
  src/gui/wxpython/wx.metadata/mdlib/mdeditorfactory.py
  src/gui/wxpython/wx.metadata/mdlib/mdgrass.py
  src/gui/wxpython/wx.metadata/mdlib/mdjinjaparser.py
  src/gui/wxpython/wx.metadata/mdlib/mdutil.py
Labels: bug, Python

#916 contributing: adds instructions on unit tests for add-ons
  CONTRIBUTING.md
  doc/development/submitting/UNIT_TESTS.md
Labels: manual

#929 contributing: Use word addon consistently
  README.md
Labels: manual

#932 checks: Fix syntax in Flake8 config
  .flake8
Labels: CI, Python

#877 v.rast.move: Move points by values from raster map
  src/vector/v.rast.move/Makefile
  src/vector/v.rast.move/examples.ipynb
  src/vector/v.rast.move/tests/conftest.py
  src/vector/v.rast.move/tests/test_v_rast_move.py
  src/vector/v.rast.move/v.rast.move.html
  src/vector/v.rast.move/v.rast.move.py
  src/vector/v.rast.move/v_rast_move.png
Labels: new addon, Python

#919 db.csw.admin: fix readfp() removed from python 3.12
  src/gui/wxpython/wx.metadata/db.csw.admin/db.csw.admin.py
Labels: bug

#918 db.csw.admin: fix SafeConfigParser() removed from python 3.12
  src/gui/wxpython/wx.metadata/db.csw.admin/db.csw.admin.py
Labels: bug, Python
