Repository OSGeo/grass-addons, pull requests merged in 2024-11, with the labels that each got.

#1215 cronjobs: expand script to run stand-alone
  utils/cronjobs_osgeo_lxd/README.md
  utils/cronjobs_osgeo_lxd/compile_addons_git.sh
  utils/cronjobs_osgeo_lxd/cron_grass_current_stable_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_current_stable_src_snapshot.sh
  utils/cronjobs_osgeo_lxd/cron_grass_legacy_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_legacy_src_snapshot.sh
  utils/cronjobs_osgeo_lxd/cron_grass_old_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_old_src_snapshot.sh
  utils/cronjobs_osgeo_lxd/cron_grass_preview_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_preview_src_snapshot.sh
Labels: enhancement

#1238 r.maxent.predict: change parameter names to avoid conflicts when scripting
  src/raster/r.maxent.predict/r.maxent.predict.html
  src/raster/r.maxent.predict/r.maxent.predict.py
Labels: bug

#1242 r_out_legend: bugfix
  src/raster/r.out.legend/r.out.legend.py
Labels: bug

#1243 r.maxent.setup: new addon and refactoring r.maxent.predict and r.maxent.train
  src/raster/r.maxent.predict/r.maxent.predict.html
  src/raster/r.maxent.predict/r.maxent.predict.py
  src/raster/r.maxent.predict/r_maxent_predict_workflow.png
  src/raster/r.maxent.setup/Makefile
  src/raster/r.maxent.setup/r.maxent.setup.html
  src/raster/r.maxent.setup/r.maxent.setup.py
  src/raster/r.maxent.train/r.maxent.train.html
  src/raster/r.maxent.train/r.maxent.train.py
  src/raster/r.maxent.train/r_maxent_train_01.png
  src/raster/r.maxent.train/r_maxent_train_02.png
  src/raster/r.maxent.train/r_maxent_train_workflow.png
Labels: bug, new addon

#1248 v.in.gbif: bugfix - add fallback if encoding text file does not work
  src/vector/v.in.gbif/v.in.gbif.py
Labels: bug

#1250 r.recode.attr: added option to set delimiter
  src/raster/r.recode.attr/r.recode.attr.html
  src/raster/r.recode.attr/r.recode.attr.py
  src/raster/r.recode.attr/r_recode_attr_01.png
Labels: enhancement
