Repository OSGeo/grass-addons, pull requests merged in 2024-10, with the labels that each got.

#1216 r.buildvrt.gdal: silence GDAL warning and fix GDAL-GRASS driver check
  src/raster/r.buildvrt.gdal/r.buildvrt.gdal.py
Labels: bug, Python

#1225 i.eodag: Support AOIs from other mapsets (fix existence check)
  src/imagery/i.eodag/i.eodag.py
Labels: bug, Python

#934 v.kriging: fix compilation warnings
  src/vector/v.kriging/utils_kriging.c
  src/vector/v.kriging/utils_raster.c
Labels: bug, help wanted, C, backport_needed

#1228 r.vif: bugfix
  src/raster/r.vif/r.vif.py
Labels: bug

#1230 r.maxent.train: bugfix and clarification help text
  src/raster/r.maxent.train/r.maxent.train.html
  src/raster/r.maxent.train/r.maxent.train.py
Labels: bug
