Repository OSGeo/grass-addons, pull requests merged in 2024-02, with the labels that each got.

#1022 v.maxent.swd: update manual page and bugfix
  src/vector/v.maxent.swd/v.maxent.swd.html
  src/vector/v.maxent.swd/v.maxent.swd.py
Labels: bug, manual

#1027 r.flowaccumulation: Support FCELL and DCELL outputs
  src/raster/r.flowaccumulation/accumulate.c
  src/raster/r.flowaccumulation/accumulate_c.c
  src/raster/r.flowaccumulation/accumulate_cm.c
  src/raster/r.flowaccumulation/accumulate_cmz.c
  src/raster/r.flowaccumulation/accumulate_co.c
  src/raster/r.flowaccumulation/accumulate_com.c
  src/raster/r.flowaccumulation/accumulate_comz.c
  src/raster/r.flowaccumulation/accumulate_coz.c
  src/raster/r.flowaccumulation/accumulate_cz.c
  src/raster/r.flowaccumulation/accumulate_d.c
  src/raster/r.flowaccumulation/accumulate_dm.c
  src/raster/r.flowaccumulation/accumulate_dmz.c
  src/raster/r.flowaccumulation/accumulate_do.c
  src/raster/r.flowaccumulation/accumulate_dom.c
  src/raster/r.flowaccumulation/accumulate_domz.c
  src/raster/r.flowaccumulation/accumulate_doz.c
  src/raster/r.flowaccumulation/accumulate_dz.c
  src/raster/r.flowaccumulation/accumulate_f.c
  src/raster/r.flowaccumulation/accumulate_fm.c
  src/raster/r.flowaccumulation/accumulate_fmz.c
  src/raster/r.flowaccumulation/accumulate_fo.c
  src/raster/r.flowaccumulation/accumulate_fom.c
  src/raster/r.flowaccumulation/accumulate_fomz.c
  src/raster/r.flowaccumulation/accumulate_foz.c
  src/raster/r.flowaccumulation/accumulate_funcs.h
  src/raster/r.flowaccumulation/accumulate_fz.c
  src/raster/r.flowaccumulation/global.h
  src/raster/r.flowaccumulation/main.c
  src/raster/r.flowaccumulation/r.flowaccumulation.html
Labels: enhancement, C

#1012 r.maxent.train: a new addon to train a model using Maxent
  src/raster/r.maxent.train/Makefile
  src/raster/r.maxent.train/r.maxent.train.html
  src/raster/r.maxent.train/r.maxent.train.py
  src/raster/r.maxent.train/r_maxent_train.png
Labels: new addon

#1025 r.maxent.predict: a new addon to create prediction layers based on a Maxent model
  src/raster/r.maxent.predict/Makefile
  src/raster/r.maxent.predict/r.maxent.predict.html
  src/raster/r.maxent.predict/r.maxent.predict.py
  src/raster/r.maxent.predict/r_maxent_predict_01.png
  src/raster/r.maxent.predict/r_maxent_predict_01.svg
  src/raster/r.maxent.predict/r_maxent_predict_02.png
  src/raster/r.maxent.predict/r_maxent_train.png
Labels: new addon

#1023 i.sentinel.import: do not ignore pattern when importing cloud masks
  src/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py
Labels: Python
