Repository OSGeo/grass-addons, pull requests merged in 2024-08, with the labels that each got.

#1096 r.windfetch: addon for computing wind fetch
  src/raster/r.windfetch/Makefile
  src/raster/r.windfetch/r.windfetch.html
  src/raster/r.windfetch/r.windfetch.py
  src/raster/r.windfetch/r_windfetch.ipynb
  src/raster/r.windfetch/r_windfetch.png
  src/raster/r.windfetch/testsuite/test_r_windfetch.py
Labels: new addon, Python

#1168 cronjob: fix old stable build (G83)
  utils/cronjobs_osgeo_lxd/README.md
  utils/cronjobs_osgeo_lxd/cron_grass_legacy_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_old_build_binaries.sh
  utils/cronjobs_osgeo_lxd/grass-addons-index.sh
Labels: bug, CI

#1143 r.in.vect: new addon to import a vector map as raster layer
  src/raster/r.in.vect/Makefile
  src/raster/r.in.vect/r.in.vect.html
  src/raster/r.in.vect/r.in.vect.py
  src/raster/r.in.vect/r_in_vect_im01.png
  src/raster/r.in.vect/r_in_vect_im02.png
  src/raster/r.in.vect/r_in_vect_im03.png
  src/raster/r.in.vect/r_in_vect_im04.png
Labels: new addon

#1172 cronjob: full path to hugo binaries
  utils/cronjobs_osgeo_lxd/hugo_clean_and_update_job.sh
Labels: bug

#1173 cronjob: fix red new version box injection and script documentation
  utils/cronjobs_osgeo_lxd/cron_grass_current_stable_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_current_stable_src_snapshot.sh
  utils/cronjobs_osgeo_lxd/cron_grass_legacy_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_legacy_src_snapshot.sh
  utils/cronjobs_osgeo_lxd/cron_grass_old_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_old_src_snapshot.sh
  utils/cronjobs_osgeo_lxd/cron_grass_preview_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_preview_src_snapshot.sh
Labels: bug, CI

#1190 v.in.gbif: bugfixes
  src/vector/v.in.gbif/v.in.gbif.py
Labels: bug, Python
