Repository OSGeo/grass-addons, pull requests merged in 2024-01, with the labels that each got.

#1006 i.histo.match: use data from example in manual and fix region
  src/imagery/i.histo.match/testsuite/test_i_histo_match.py
Labels: bug, CI, Python

#1011 v.scatterplot: print regression equation to screen
  src/vector/v.scatterplot/v.scatterplot.html
  src/vector/v.scatterplot/v.scatterplot.py
Labels: enhancement

#1007 i.histo.match: replace SQLite with numpy and parallelize
  src/imagery/i.histo.match/i.histo.match.html
  src/imagery/i.histo.match/i.histo.match.py
  src/imagery/i.histo.match/testsuite/test_i_histo_match.py
Labels: enhancement, Python

#1008 [Bug] Fix or replace i.pr Perl scripts which fail with perlcritic
  src/imagery/i.pr/PRLIB/extract_functions.pl
  src/imagery/i.pr/PRLIB/extract_ps.pl
Labels: bug, Perl

#993 v.civil: Fixed Improper Method Call: `__setitem__`
  src/vector/v.civil/road_tables.py
Labels: bug

#997 r.fusion: lowres-highres image fusion
  src/raster/r.fusion/Makefile
  src/raster/r.fusion/r.fusion.html
  src/raster/r.fusion/r.fusion.py
Labels: new addon, Python

#1001 r.edm.eval: port shell/R script to Python
  src/raster/r.edm.eval/r.edm.eval.html
  src/raster/r.edm.eval/r.edm.eval.py
  src/raster/r.edm.eval/r.edm.eval.sh
  src/raster/r.edm.eval/r_edm_eval_01.png
  src/raster/r.edm.eval/r_edm_eval_02.png
Labels: Python

#1014 i.fusion.hpf: fix import funcs from high_pass_filter module
  src/imagery/i.fusion.hpf/i.fusion.hpf.py
Labels: bug, Python

#1009 v.maxent.swd: bug fixes and new option to export explanatory raster layers
  src/vector/v.maxent.swd/v.maxent.swd.html
  src/vector/v.maxent.swd/v.maxent.swd.py
Labels: bug, enhancement

#1018 v.what.rast.multi.py: deal with @ in column names
  src/vector/v.what.rast.multi/v.what.rast.multi.py
Labels: bug, enhancement

#1002 i.sentinel.mask: refactor and add sun_position and output option
  src/imagery/i.sentinel/i.sentinel.mask/i.sentinel.mask.py
Labels: enhancement, Python
