Repository OSGeo/grass-addons, pull requests merged in 2024-06, with the labels that each got.

#1044 i.sentinel.download: various improvements
  src/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py
Labels: enhancement

#979 m.prism.download: Add a new addon for downloading PRISM climate data
  src/misc/m.prism.download/Makefile
  src/misc/m.prism.download/m.prism.download.html
  src/misc/m.prism.download/m.prism.download.py
Labels: new addon

#1092 manual: update broken URLs
  src/raster/r.sim.water.mp/r.sim.water.mp.html
  src/raster/r.soillossbare/r.soillossbare.html
  src/vector/v.transects/v.transects.html
Labels: manual

#1090 i.eodag: add i.eodag module
  src/imagery/i.eodag/Makefile
  src/imagery/i.eodag/i.eodag.html
  src/imagery/i.eodag/i.eodag.py
Labels: new addon, Python, gsoc

#1093 v.nnstat: fix bool compilation error
  src/vector/v.nnstat/getval.c
  src/vector/v.nnstat/local_proto.h
  src/vector/v.nnstat/main.c
  src/vector/v.nnstat/mbb.c
  src/vector/v.nnstat/mbb.h
  src/vector/v.nnstat/nearest_neighbour.c
  src/vector/v.nnstat/spatial_index.c
Labels: C

#1101 style: use `is True` instead of `== True`
  src/raster/r.area.createweight/r.area.createweight.py
  src/raster/r.mcda.roughset/r.mcda.roughset.py
Labels: Python

#1100 r.mcda.roughset: fix Poznań University link
  src/raster/r.mcda.roughset/r.mcda.roughset.html
Labels: bug, manual

#1107 cronjobs: no need to use chgrp on files
  utils/cronjobs_osgeo_lxd/cron_grass_legacy_src_snapshot.sh
  utils/cronjobs_osgeo_lxd/cron_grass_new_current_src_snapshot.sh
  utils/cronjobs_osgeo_lxd/cron_grass_old_current_src_snapshot.sh
  utils/cronjobs_osgeo_lxd/cron_grass_preview_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_preview_src_snapshot.sh
Labels: CI

#1105 docs: wrong URI in SUBMITTING
  CONTRIBUTING.md
  README.md
  SUBMITTING
Labels: manual

#1132 CI(super-linter): Use default log level for super-linter
  .github/workflows/super-linter.yml
Labels: CI

#1133 style: Fix current flake8 errors
  src/general/g.projpicker/g.projpicker.py
  src/hadoop/hd/hdfsgrass/hdfs_grass_lib.py
  src/hadoop/hd/hdfswrapper/hive_hook.py
  src/hadoop/hd/hdfswrapper/security_utils.py
  src/hadoop/hd/hdfswrapper/webhdfs_hook.py
  src/imagery/i.landsat8.swlst/column_water_vapor.py
  src/imagery/i.landsat8.swlst/split_window_lst.py
  src/imagery/i.modis/libmodis/rmodislib.py
  src/misc/m.printws/m.printws.py
  src/raster/r.area.createweight/r.area.createweight.py
  src/raster/r.category.trim/r.category.trim.py
  src/raster/r.estimap.recreation/estimap_recreation/accessibility.py
  src/raster/r.estimap.recreation/estimap_recreation/demand.py
  src/raster/r.estimap.recreation/estimap_recreation/mobility.py
  src/raster/r.estimap.recreation/estimap_recreation/spectrum.py
  src/raster/r.futures/r.futures.demand/r.futures.demand.py
  src/raster/r.green/r.green.hydro/libhydro/plant.py
  src/raster/r.green/r.green.hydro/r.green.hydro.financial/r.green.hydro.financial.py
  src/raster/r.green/r.green.hydro/r.green.hydro.optimal/r.green.hydro.optimal.py
  src/raster/r.green/r.green.hydro/r.green.hydro.theoretical/r.green.hydro.theoretical.py
  src/raster/r.maxent.train/r.maxent.train.py
  src/vector/v.class.mlpy/v.class.mlpy.py
Labels: CI, Python
