Repository OSGeo/grass-addons, pull requests merged in 2024-12, with the labels that each got.

#1241 cronjobs: inject canonical URLs into older manual pages (SEO)
  utils/cronjobs_osgeo_lxd/cron_grass_current_stable_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_legacy_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_old_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_preview_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_job_list_grass
  utils/cronjobs_osgeo_lxd/robots.txt
Labels: manual, CI

#1254 v.stream.profiler: fix lazy loading of matplotlib
  src/vector/v.convert.all/v.convert.all.html
  src/vector/v.scatterplot/v.scatterplot.py
  src/vector/v.stream.profiler/v.stream.profiler.py
Labels: bug

#1255 v.maxent.swd: Fix overwrite behavior for existing species SWD file
  src/vector/v.maxent.swd/v.maxent.swd.py
Labels: bug

#1227 r.watersheds: New addon for OpenMP parallel watershed delineation based on Cho (2025)
  src/raster/r.watersheds/Makefile
  src/raster/r.watersheds/delineate.c
  src/raster/r.watersheds/delineate_funcs.h
  src/raster/r.watersheds/delineate_lessmem.c
  src/raster/r.watersheds/delineate_moremem.c
  src/raster/r.watersheds/gettimeofday.c
  src/raster/r.watersheds/global.h
  src/raster/r.watersheds/main.c
  src/raster/r.watersheds/outlet_list.c
  src/raster/r.watersheds/r.watersheds.html
  src/raster/r.watersheds/r_watersheds_formats.png
  src/raster/r.watersheds/r_watersheds_nc_example.png
  src/raster/r.watersheds/raster_map.c
  src/raster/r.watersheds/timeval_diff.c
Labels: new addon, C

#1264 r.maxent.train.py: fixes wrong handling of end of line character
  src/raster/r.maxent.train/r.maxent.train.py
Labels: bug, Python

#1269 g.citation.py: bugfix
  src/general/g.citation/g.citation.py
Labels: bug

#1270 r.maxent.train: Prevent use of scientific notation for precision number
  src/raster/r.maxent.predict/r.maxent.predict.html
  src/raster/r.maxent.setup/r.maxent.setup.html
  src/raster/r.maxent.train/r.maxent.train.html
  src/raster/r.maxent.train/r.maxent.train.py
  src/vector/v.maxent.swd/v.maxent.swd.html
Labels: bug, manual

#1271 v.boxplot and r.boxplot: plot/layout options added / changed
  src/raster/r.boxplot/r.boxplot.html
  src/raster/r.boxplot/r.boxplot.py
  src/vector/v.boxplot/v.boxplot.html
  src/vector/v.boxplot/v.boxplot.py
Labels: enhancement, manual, Python

#1274 various addons: Removed trailing spaces at line ends in html pages
  src/raster/r.boxplot/r.boxplot.html
  src/raster/r.maxent.predict/r.maxent.predict.html
  src/raster/r.maxent.setup/r.maxent.setup.html
  src/raster/r.maxent.train/r.maxent.train.html
  src/raster/r.mess/r.mess.html
  src/raster/r.recode.attr/r.recode.attr.html
  src/vector/v.boxplot/v.boxplot.html
  src/vector/v.maxent.swd/v.maxent.swd.html
Labels: bug, manual
