Repository OSGeo/grass-addons, pull requests merged in 2024-03, with the labels that each got.

#1031 CI: Modernize workflows and adding concurrency groups to cancel outdated jobs
  .github/workflows/black.yml
  .github/workflows/ci.yml
  .github/workflows/clang-format-check.yml
  .github/workflows/flake8.yml
  .github/workflows/super-linter.yml
  src/raster/r.findtheriver/README.md
  src/raster/r.landscape.evol/r.landscape.evol.md
Labels: CI

#1034 cronjobs: fix new version red boxes in older manuals
  utils/cronjobs_osgeo_lxd/cron_grass_legacy_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_old_current_build_binaries.sh
Labels: manual

#1038 CI(clang-format): Post fixes as code suggestions if possible when running on a PR
  .github/workflows/clang-format-check.yml
  .github/workflows/post-pr-reviews.yml
Labels: CI, C, C++

#1021 v.multi2singlepart: a new addon to split multipart to singlepart polygons
  src/vector/v.multi2singlepart/Makefile
  src/vector/v.multi2singlepart/example.png
  src/vector/v.multi2singlepart/example.svg
  src/vector/v.multi2singlepart/v.multi2singlepart.html
  src/vector/v.multi2singlepart/v.multi2singlepart.py
Labels: new addon

#1043 r.in.ahn: new addon to import the AHN DTM or DSM
  src/raster/r.in.ahn/Makefile
  src/raster/r.in.ahn/r.in.ahn.html
  src/raster/r.in.ahn/r.in.ahn.py
  src/raster/r.in.ahn/r_in_ahn_01.png
  src/raster/r.in.ahn/r_in_ahn_02.png
Labels: new addon
