Repository OSGeo/grass-addons, pull requests merged in 2024-09, with the labels that each got.

#1195 cronjob: fix file name extension of REQUIREMENTS
  utils/cronjobs_osgeo_lxd/cron_grass_old_src_snapshot.sh
Labels: bug, CI

#1188 t.rast.import.netcdf: handle empty CRS and no subdataset
  .github/workflows/apt.txt
  .github/workflows/ci.yml
  .github/workflows/extra_requirements.txt
  src/temporal/t.rast.import.netcdf/t.rast.import.netcdf.html
  src/temporal/t.rast.import.netcdf/t.rast.import.netcdf.py
  src/temporal/t.rast.import.netcdf/testsuite/test_t_rast_import_netcdf.py
Labels: bug, Python

#1207 cronjob: fix configuration flags for BLAS and LAPACK
  utils/cronjobs_osgeo_lxd/cron_grass_current_stable_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_legacy_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_old_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_preview_build_binaries.sh
Labels: CI

#1208 cronjob: drop to copy over CHANGES file
  utils/cronjobs_osgeo_lxd/cron_grass_current_stable_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_current_stable_src_snapshot.sh
  utils/cronjobs_osgeo_lxd/cron_grass_legacy_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_legacy_src_snapshot.sh
  utils/cronjobs_osgeo_lxd/cron_grass_old_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_old_src_snapshot.sh
  utils/cronjobs_osgeo_lxd/cron_grass_preview_build_binaries.sh
  utils/cronjobs_osgeo_lxd/cron_grass_preview_src_snapshot.sh
Labels: CI

#1209 r.buildvrt.gdal: Create GDAL VRTs for GDAL linked raster maps
  src/raster/r.buildvrt.gdal/Makefile
  src/raster/r.buildvrt.gdal/r.buildvrt.gdal.html
  src/raster/r.buildvrt.gdal/r.buildvrt.gdal.py
  src/raster/r.buildvrt.gdal/testsuite/test_r_buildvrt_gdal.py
Labels: new addon, Python
