Repository OSGeo/grass-addons, pull requests merged in 2025-02, with the labels that each got.

#1300 r.subdayprecip.design: do not limit raster names by return periods
  src/raster/r.subdayprecip.design/r.subdayprecip.design.py
Labels: enhancement, Python

#1309 CI: Update the actions to be able to run grass7 workflows
  .github/workflows/ci.yml
Labels: CI

#1244 i.sam2: SamGeo2 model
  src/imagery/i.sam2/Makefile
  src/imagery/i.sam2/i.sam2.html
  src/imagery/i.sam2/i.sam2.py
  src/imagery/i.sam2/i_sam2_trees.jpg
  src/imagery/i.sam2/requirements.txt
  src/imagery/i.sam2/testsuite/test_i_sam2.py
Labels: new addon, Python

#1315 i.sam2: Fix unaddressed ruff errors
  src/imagery/i.sam2/i.sam2.py
Labels: Python

#1327 r.slopeunits.clean: fix input option
  src/raster/r.slopeunits/r.slopeunits.clean/r.slopeunits.clean.py
Labels: Python

#1331 cronjonb: simplify hugo cronjob by using rsync
  utils/cronjobs_osgeo_lxd/README.md
  utils/cronjobs_osgeo_lxd/hugo_clean_and_update_job.sh
Labels: enhancement, CI

#1348 docs: fix HTML errors in r.hand.html
  src/raster/r.hand/r.hand.html
Labels: bug
