Repository OSGeo/grass-addons, pull requests merged in 2025-07, with the labels that each got.

#1439 r.maxent.setup: bugfixes and added checks
  src/raster/r.maxent.setup/r.maxent.setup.py
Labels: bug

#1441 chore: Update .gitignore to include some changes from upstream GRASS repo
  .gitignore
Labels: CI

#1443 r.lfp: Add a new longest flow path addon
  src/raster/r.lfp/Makefile
  src/raster/r.lfp/direction.c
  src/raster/r.lfp/gettimeofday.c
  src/raster/r.lfp/global.h
  src/raster/r.lfp/lfp_funcs.h
  src/raster/r.lfp/main.c
  src/raster/r.lfp/outlet_list.c
  src/raster/r.lfp/outlets.c
  src/raster/r.lfp/point_list.c
  src/raster/r.lfp/r.lfp.html
  src/raster/r.lfp/r.lfp.md
  src/raster/r.lfp/r_lfp_custom_formats.png
  src/raster/r.lfp/r_lfp_elev_state_500m_example.png
  src/raster/r.lfp/r_lfp_elevation_example.png
  src/raster/r.lfp/r_lfp_formats.png
  src/raster/r.lfp/timeval_diff.c
  src/raster/r.lfp/write.c
Labels: new addon
