Repository OSGeo/grass-addons, pull requests merged in 2025-05, with the labels that each got.

#1393 r.slopeunits: add references
  src/raster/r.slopeunits/r.slopeunits.clean/r.slopeunits.clean.html
  src/raster/r.slopeunits/r.slopeunits.clean/r.slopeunits.clean.md
  src/raster/r.slopeunits/r.slopeunits.create/r.slopeunits.create.html
  src/raster/r.slopeunits/r.slopeunits.create/r.slopeunits.create.md
  src/raster/r.slopeunits/r.slopeunits.html
  src/raster/r.slopeunits/r.slopeunits.md
  src/raster/r.slopeunits/r.slopeunits.metrics/r.slopeunits.metrics.html
  src/raster/r.slopeunits/r.slopeunits.metrics/r.slopeunits.metrics.md
  src/raster/r.slopeunits/r.slopeunits.optimize/r.slopeunits.optimize.html
  src/raster/r.slopeunits/r.slopeunits.optimize/r.slopeunits.optimize.md
Labels: manual

#1396 cronjobs: fix G84 patch version
  utils/cronjobs_osgeo_lxd/cron_grass_current_stable_build_binaries.sh
Labels: CI

#1402 r.earthworks: initial release of terrain modeling tool
  src/raster/r.earthworks/Makefile
  src/raster/r.earthworks/r.earthworks.html
  src/raster/r.earthworks/r.earthworks.md
  src/raster/r.earthworks/r.earthworks.py
  src/raster/r.earthworks/r_earthworks.ipynb
  src/raster/r.earthworks/r_earthworks_01.png
  src/raster/r.earthworks/r_earthworks_02.png
  src/raster/r.earthworks/r_earthworks_03.png
  src/raster/r.earthworks/r_earthworks_04.png
  src/raster/r.earthworks/r_earthworks_05.png
  src/raster/r.earthworks/r_earthworks_06.png
  src/raster/r.earthworks/r_earthworks_07.png
  src/raster/r.earthworks/r_earthworks_08.png
  src/raster/r.earthworks/r_earthworks_09.png
  src/raster/r.earthworks/r_earthworks_10.png
  src/raster/r.earthworks/testsuite/test_r_earthworks.ipynb
  src/raster/r.earthworks/testsuite/test_r_earthworks.py
Labels: new addon
