Repository OSGeo/grass-addons, pull requests merged in 2025-01, with the labels that each got.

#1276 CI: silence confusing --help output in workflows/test.sh
  .github/workflows/test.sh
Labels: bug

#1263 i.eodag: Adjust configuration to breaking changes in EODAG 3.0
  src/imagery/i.eodag/i.eodag.py
Labels: bug, Python

#1280 r.stream.snap: Fix snapping to immediate NW neighbor cell
  src/raster/r.stream.snap/snap.c
Labels: C, backport_needed

#1279 Add r.slopeunits module
  src/raster/r.slopeunits/Makefile
  src/raster/r.slopeunits/r.slopeunits.clean/Makefile
  src/raster/r.slopeunits/r.slopeunits.clean/r.slopeunits.clean.html
  src/raster/r.slopeunits/r.slopeunits.clean/r.slopeunits.clean.py
  src/raster/r.slopeunits/r.slopeunits.create/Makefile
  src/raster/r.slopeunits/r.slopeunits.create/r.slopeunits.create.html
  src/raster/r.slopeunits/r.slopeunits.create/r.slopeunits.create.py
  src/raster/r.slopeunits/r.slopeunits.html
  src/raster/r.slopeunits/r.slopeunits.metrics/Makefile
  src/raster/r.slopeunits/r.slopeunits.metrics/r.slopeunits.metrics.html
  src/raster/r.slopeunits/r.slopeunits.metrics/r.slopeunits.metrics.py
  src/raster/r.slopeunits/r.slopeunits.optimize/Makefile
  src/raster/r.slopeunits/r.slopeunits.optimize/r.slopeunits.optimize.html
  src/raster/r.slopeunits/r.slopeunits.optimize/r.slopeunits.optimize.py
  src/raster/r.slopeunits/testsuite/test_r_slopeunits.py
Labels: new addon, Python

#1283 r.slopeunits.optimize: clean up tmp mapsets
  src/raster/r.slopeunits/r.slopeunits.optimize/r.slopeunits.optimize.py
Labels: bug, Python

#1284 r.slopeunits: fix import of grass.scripts
  src/raster/r.slopeunits/r.slopeunits.clean/r.slopeunits.clean.py
  src/raster/r.slopeunits/r.slopeunits.create/r.slopeunits.create.py
  src/raster/r.slopeunits/r.slopeunits.metrics/r.slopeunits.metrics.py
  src/raster/r.slopeunits/r.slopeunits.optimize/r.slopeunits.optimize.py
Labels: bug

#1289 v.multi2singlepart: fix issue #1277
  src/vector/v.multi2singlepart/v.multi2singlepart.py
Labels: bug
